#!/bin/bash
#Data: 26-08-2021
#Author: Szymon Szymczewski

echo "Enter the car brand"
read brand


webpage=$(curl 'https://www.amazon.com/Emblem-Wheel-Center-Steering-Replacement/dp/B094HVYX44/ref=sr_1_1?dchild=1&keywords=bmw&qid=1629964289&sr=8-1' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed > tmp.html)
#firefox tmp.html
#echo at tmp.html | pup 'span#priceblock_ourprice text{}'
#cat tmp.html | pup 'span#priceblock_ourprice text{}' | sed 's/^.//g' | cut -d. -f1
price=$(echo '$webpage'  | pup 'span#priceblock_ourprice text{}' | sed 's/^.//g' )
echo $price



