#!/bin/bash
#Data: 25-08-2021
#Author: Szymon Szymczewski

remover(){

if [ $REPLY = 1 ]
	then
	for file in $PWD/*
		do
			if [ -d $file ]
				then
				rmdir $file
			fi
		done
elif [ $REPLY = 2 ]
	then
	for file in $PWD/*
	do
		if [ ! -s $file ]
			then
			rm -f $file
		fi
	done
elif [ $REPLY = 3 ]
	then
	for file in $PWD/*.html
	do
		rm -f $file
	done	
elif [ $REPLY = 4 ]
	then
	for file in $PWD/*.txt
	do
		rm -f $file
	done
else
	echo "Try try try"
fi
}
choice="Dir File Html txt"

select option in $choice; do
if [ $REPLY = 1 ]
         then
                 remover $REPLY
         exit 1
elif [ $REPLY = 2 ]
		then
                 remover $REPLY
         exit 1
elif [ $REPLY = 3 ]
		then
		remover $REPLY
	 exit 1
elif [ $REPLY = 4 ]
		then
		remover $REPLY
	exit 1
else
	echo "Try again"
fi
done


