#!/bin/bash
#Data: 26-08-2021
#Author: Szymon Szymczewski

echo "Enter the car brand: "
read car_brand

webpage=$(curl https://www.otomoto.pl/osobowe/$car_brand/ > $car_brand.html)
#firefox $car_brand.html
brand_page=$car_brand.html

echo $brand_page
#cat $brand_page | pup 'div[class="offer-item__wrapper"]'

cat $brand_page | pup '.offer-item.is-row .offer-title__link text{}'


