#!/bin/bash

#Random Password Generator 
#Author: Szymon Szymczewski 

echo "Enter the lenght of the password: "
read length

#Mozemy zmienic sekwencje zeby wygenerowal wiecej hasel np seq 1 7
for i in $(seq 1 7);
do
#Generujemy za pomoca ssl randomowe znaki w base64(Mozna uzyc innego, ale to sa slabsze np. -hex 48), uzywamy 48 znakow i ucinamy od 1 znaku do length 
openssl rand -base64 48 | cut -c1-$length
done


